### ISSUE TITLE
Test with BBR and Pacing

### ISSUE THREAD

**Issue by yangchi** [lnicco/mvfst-qns#1]
This is running Cubic: https://github.com/lnicco/mvfst-qns/blob/64ad6e2e9ba255f0f07e48f468c6c841b71849a3/run_endpoint.sh#L75

**Comment by yangchi** [comment]
can you add a `-congestion=bbr -pacing=true` there? Thanks!

**Comment by yangchi** [comment]
Oh I think the default batch mode is none. So also add a `-quic_batch_mode=1` would be great

**Comment by lnicco** [comment]
uppsala! 

I accept PRs :) 
but I’ll fix this one

**Comment by lnicco** [comment]
ok, fixed. 
should we just default to bbr+pacing in hq ??

**Comment by yangchi** [comment]
I don't know dude

**Comment by yangchi** [comment]
I think your latest commit missed GSO? It fixed pacing and bbr though.
Thank you for doing this!

**Comment by lnicco** [comment]
yeah, I reopened it when I realized that. 
Note to self: commit from mobile is not recommended :)
